# Generated by Django 4.2.7 on 2023-11-07 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=255)),
                ('floor', models.IntegerField()),
                ('number', models.CharField(max_length=10)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('has_video_projector', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('unit_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('semester', models.CharField(max_length=5)),
                ('exam_date', models.DateField()),
                ('days', models.BinaryField(max_length=1)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_registration.classroom')),
                ('course', models.ForeignKey(db_column='course_code', on_delete=django.db.models.deletion.DO_NOTHING, to='course_registration.course')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('national_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course_registration.person')),
                ('student_number', models.CharField(max_length=10, unique=True)),
                ('enrollment_year', models.CharField(max_length=4)),
                ('major', models.CharField(max_length=255)),
            ],
            bases=('course_registration.person',),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_registration.coursegroup')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course_registration.person')),
                ('staff_number', models.CharField(max_length=10, unique=True)),
                ('hiring_date', models.DateField()),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_registration.department')),
            ],
            bases=('course_registration.person',),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course_registration.coursegroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course_registration.student')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='head_of_department',
            field=models.ForeignKey(blank=True, db_column='head', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_of_department', to='course_registration.professor'),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='offered_by',
            field=models.ForeignKey(db_column='offered_by', on_delete=django.db.models.deletion.CASCADE, to='course_registration.professor'),
        ),
    ]
